apiVersion: v1
#Creating service
kind: Service
metadata:
  name: my-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app
#Creating LoadBalancer that exposes the app on port 443
#and forwards the traffic to the pods on port 30100
  type: LoadBalancer
  ports:
  - nodePort : 30100
    protocol: TCP
    port: 443 
    targetPort: 443
  
